name: 'My first github action'

on: [ 'push', 'pull_request' ]

jobs:
  first-job:
    name: 'first job'

    runs-on: ubuntu-latest

    steps:
    - name: this first job step 1
      shell: bash
      run: |
        echo "Hello World"
    - name: this first job step 2
      shell: bash
      run: |
        echo "Hello World"
  second-job:
    name: 'second job'
    needs: first-job

    runs-on: ubuntu-latest

    steps:
    - name: this second job step 1 
      shell: bash
      run: |
        echo "Hello World"
  
  third-job:
    name: 'third job'
    needs: second-job

    runs-on: ubuntu-latest

    steps:
    - name: this third job step 1 
      shell: bash
      run: |
        echo "Hello World"